stocks = {
    ### ? Default Jones
    # 'GOLL4.SA': 'GOL',
    # 'CVCB3.SA': 'CVC',
    # 'WEGE3.SA': 'WEGE',
    # 'MGLU3.SA': 'MGLU',
    # 'TOTS3.SA': 'TOTS',
    # 'BOVA11.SA': 'BOVA'
    ### ? EUA & China high tecnology
    "MSFT": "MICROSOFT",
    "AAPL": "APPLE",
    "GOOGL": "GOOGLE",
    "AMZN": "AMAZON",
    "TSLA": "TESLA",
    "META": "META",
    "ORCL": "ORACLE",
    "NVDA": "NVIDIA",
    "BABA": "ALIBABA",
    "TCEHY": "TENCENT",
    "BIDU": "BAIDU",
    ### ? Benzi
    # "BBAS3.SA": "BANCO DO BRASIL",
    # "ITSA3.SA": "ITAUSA",
    # "EGIE3.SA": "ENGIE BRASIL",
    # "SANB3.SA": "BANCO SANTANDER (BRASIL)",
    # "ABEV3.SA": "AMBEV",
    # "B3SA3.SA": "BRASIL BOLSA BALCAO",
    # "WEGE3.SA": "WEGE",
    # "BBDC3.SA": "BANCO BRADESCO",
    # "SAPR3.SA": "COMPANHIA DE SANEAMENTO PARANA SANEPAR",
    # "BBSE3.SA": "BB SEGURIDADE",
    # "KLBN3.SA": "KLABIN SA",
    # "TRPL3.SA": "ISA CTEEP",
    # "VIVA3.SA": "VIVARA PARTICIPACOES",
    # "SBSP3.SA": "SABESP",
    # "MDIA3.SA": "M. DIAS BRANCO",
    # "TAEE3.SA": "TAESA",
    # "FLRY3.SA": "FLEURY",
    # "PATI3.SA": "PANATLANTICA",
}
